spring:
  profiles:
    active: ${spring.profiles.active}

#ローカル環境用
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8

#開発環境用
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
    

# 単体テスト環境用
---
spring:
  profiles: unit
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_ON_EXIT=FALSE;characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    data: data-unit.sql
    sql-script-encoding: UTF-8

---  
spring:
  messages:
    basename: message/messages
    cache-seconds: -1
    encoding: UTF-8