spring:
  profiles:
    active: ${spring.profiles.active}

#ローカル環境用
---
#spring:
#  profiles: local
#  datasource:
#    url: jdbc:h2:mem:AZ;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    sql-script-encoding: UTF-8
spring:
  profiles: local
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://${database.host}/${database.name}?currentSchema=${database.schema}&user=${database.user}&password=${database.password}&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driverClassName: org.postgresql.Driver
    sql-script-encoding: UTF-8


#開発環境用
---
spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none  
  datasource:
    platform: postgres
    url: jdbc:postgresql://${database.host}/${database.name}?currentSchema=${database.schema}&user=${database.user}&password=${database.password}&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driverClassName: org.postgresql.Driver
    sql-script-encoding: UTF-8
    

# 単体テスト環境用
---
spring:
  profiles: unit
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_ON_EXIT=FALSE;characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    data: data-unit.sql
    sql-script-encoding: UTF-8

---  
spring:
  messages:
    basename: message/messages
    cache-seconds: -1
    encoding: UTF-8